### ISSUE TITLE
Can this library Add a method to get the boundingbox of the path

### ISSUE THREAD

**Issue by steven-spec** [pdfmm/pdfmm#39]
like minAreaRect  method in opencv

**Comment by steven-spec** [comment]
Glad you could reply，  i think the method could be add in the render module， use to calculate the min rect of the path(eg. moveto lineto  CubicBezierTo etc..)

**Comment by ceztko** [comment]
You probably mean the `PdfPainter` class (please confirm), which is more about drawing/imposing, since we don't have a render viewer. That class improved compared to PoDoFo, but would still need some love with regard to validation of operations being fed. One idea would be also to have an API that resembles javascript [`CanvasRenderingContext2D`](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D).
Adding a function to compute the bounding box would work only on the current path being built, because there's no class representing a path. For what I understand of your needs it would be an equivalent of  this [clipBoundingRect](https://doc.qt.io/qt-6/qpainter.html#clipBoundingRect) of qt `QPainter` class. I'm sorry but I can't promise such function. Any improvement/cleaning of the `PdfPainter` API would be welcome.

**Comment by steven-spec** [comment]
yes you are right , i mean  adding a function  on the current path being built，then compute the bounding box .  I describe  error. 
i saw you have plan to add a render module so i think add the function in render module.  for now, the function add in pdfpainter is better.   thanks!

**Comment by ceztko** [comment]
The project has been moved back to [PoDoFo](https://github.com/podofo/podofo)
